### ISSUE TITLE
OnExpiredHandler異常

### ISSUE THREAD

**Issue by ericeric284** [fs-tw/Further.Operation#8]
1. OnExpiredHandler 如果處理OperationExpiredEto失敗，有可能會無限重試(RabbitMQ的特性)
建議加上TryCatch後記錄Log，或是重試N次再丟掉

2. 我這邊看到的錯誤是operation重複ID導致寫入失敗(資料庫已經有該筆資料)，若有重現方式會再補上

**Comment by yinchang0626** [comment]
@ggoch 
需要例外處理，
但需確定會有重複Id 的原因是如何引起的，又相同Id 有相同的資料嗎？

**Comment by ericeric284** [comment]
# 測試結論
測試如下，推測是RabbitMQ行為導致

目前各個Host(後台網站, WinApp, WindowsService)都共用了同一個Exchange
並且在開發環境為了方便測試，都有啟用監聽Further.Abp.Operation.OperationExpiredEto事件

當發出訊息時，所有Host都會收到Further.Abp.Operation.OperationExpiredEto事件 (若Host沒啟動，RabbitMQ會存起來等你去收)
因此當我切換到其他Host時，就會重複處理同一個Operation事件導致出錯

=>正式環境會設定只有WindowsService監聽並寫入資料庫，所以不會遇到這個問題

## 0403整理
- Eto預設會發送給同Exchange內的所有Client，若使用EventHandler須注意
- 如 @ggoch 下面的測試提到的，若同Exchange和ClientName的場合，會由RabbitMQ隨機分配訊息 =>可以做為LoadBalance

# 測試範例:
WinApp加入一筆Operation，RabbitMQ上會看到 後台網站, WinApp, WindowsService都會產生一筆訊息

附圖是我在WinApp加入一筆，所有其他Queue也會收到一筆
WinApp自己收到一筆因此是0
![image](https://github.com/fs-tw/Further.Operation/assets/74721170/87e8f7f5-0572-4381-b32b-79fb698d08f8)

# 附件: AppSettings 設定值
```js
//WinAPP
 "EventBus": {
   "ClientName": "WB.WinApp",
   "ExchangeName": "WB"
 }
//後台網站
"EventBus": {
  "ClientName": "WB.HttpApi.Host",
  "ExchangeName": "WB"
}
//WindowsService
  "EventBus": {
    "ClientName": "WB.WindowsService",
    "ExchangeName": "WB"
  }
```

**Comment by yinchang0626** [comment]
@ggoch 請用全新的專案有api.host 和console模擬上述設定觀察amq是否有相同結果
測試結果建立文件回Further docs

**Comment by ggoch** [comment]
https://jim-5.gitbook.io/rabbitmq/san-zhongexchange-mo-shi

volo 預設使用Direct，不同的queue只要有註冊routekey皆會收到，跟ExchangeName設定無關，
假設有兩個host設定一樣的queue，那事件收到隨機

```c#
channel.BasicPublish(
    exchange: AbpRabbitMqEventBusOptions.ExchangeName,
    routingKey: eventName,
    mandatory: true,
    basicProperties: properties,
    body: body
);
```

**Comment by yinchang0626** [comment]
@ggoch 你說明的部分有跟 @ericeric284 測試的結果不同嗎？
ClientName就是Queue的key嗎

**Comment by ggoch** [comment]
> @ggoch 你說明的部分有跟 @ericeric284 測試的結果不同嗎？ ClientName就是Queue的key嗎

測試結果一樣，client是queueKey沒錯，然後同時有多個client用同個queueKey不會輪流執行，是隨機執行

**Comment by ChangYinShung** [comment]
移動 文件 https://docs.further.stage.furthersoftware.com.tw/zh-Hant/further/latest/RabbitMQ/Index
